import { daysAgo, now, act } from './dates.js';


export const SEED_OPPS = [
  {
    id: "OPP-1027",
    customer: "Cape Ann Coffee Roasters",
    contact: { name: "Elise Moreau", email: "elise@capeanncoffee.com" },
    product: "Cardamom twist bun — second product line",
    createdBy: "u1",
    createdAt: daysAgo(2),
    stage: "discovery",
    stageEnteredAt: daysAgo(2),
    conversations: [
      { by: "u1", at: daysAgo(2), note: "Elise called — the espresso morning bun is selling out daily. Wants a second pastry in time for fall." },
    ],
    formulations: { requested: false, status: "n/a", notes: "" },
    sampleRequest: null,
    samples: [],
    sampleFinalized: false,
    pricing: { status: "not_requested", base: null, addons: [], invoiceTotal: null, invoiceSentAt: null, poNumber: null, poReceivedAt: null },
    onboarding: { specSource: null, specStatus: "not_started", metadataMapped: false, label: null, approval: { status: "not_started", by: null, at: null, notes: "" } },
    activity: [
      act(daysAgo(2), "u1", "Opportunity created — returning customer (first product BBC-EMB-095-C1 in production since May)"),
    ],
    discussion: [],
  },
  {
    id: "OPP-1026",
    customer: "Little Compton Creamery",
    contact: { name: "Sarah Whitfield", email: "sarah@lccreamery.com" },
    product: "Gluten-free shortbread base for ice cream sandwiches",
    createdBy: "u1",
    createdAt: daysAgo(3),
    stage: "sample_request",
    stageEnteredAt: daysAgo(1),
    conversations: [
      { by: "u1", at: daysAgo(3), note: "Intro call. They want a GF shortbread that holds up frozen." },
      { by: "u1", at: daysAgo(2), note: "Second call — volume est. 4k units/mo. Interested in a sample." },
    ],
    formulations: { requested: true, status: "pending", notes: "" },
    sampleRequest: null,
    samples: [],
    sampleFinalized: false,
    pricing: { status: "not_requested", base: null, addons: [], invoiceTotal: null, invoiceSentAt: null, poNumber: null, poReceivedAt: null },
    onboarding: { specSource: null, specStatus: "not_started", metadataMapped: false, label: null, approval: { status: "not_started", by: null, at: null, notes: "" } },
    activity: [
      act(daysAgo(3), "u1", "Opportunity created after intro call"),
      act(daysAgo(1), "u1", "Sent to Sample Request team, and simultaneously to Formulations (GF base needs formulation work)"),
    ],
    discussion: [
      { by: "u2", at: daysAgo(1), text: "Is this certified-GF or just gluten-free recipe? Changes which line we can quote for the sample." },
      { by: "u1", at: daysAgo(1), text: "They asked about certification — assume certified-GF for now, I'll confirm on Thursday's call." },
    ],
  },
  {
    id: "OPP-1025",
    customer: "Beacon Hill Bagel Co.",
    contact: { name: "Marcus Chen", email: "marcus@bhbagel.com" },
    product: "Everything-seasoning focaccia squares, wholesale",
    createdBy: "u1",
    createdAt: daysAgo(4),
    stage: "discovery",
    stageEnteredAt: daysAgo(4),
    conversations: [
      { by: "u1", at: daysAgo(4), note: "Met at the Seaport food expo. Wants a savory grab-and-go item." },
      { by: "u1", at: daysAgo(1), note: "Follow-up call — comparing us against two other suppliers." },
    ],
    formulations: { requested: false, status: "n/a", notes: "" },
    sampleRequest: null,
    samples: [],
    sampleFinalized: false,
    pricing: { status: "not_requested", base: null, addons: [], invoiceTotal: null, invoiceSentAt: null, poNumber: null, poReceivedAt: null },
    onboarding: { specSource: null, specStatus: "not_started", metadataMapped: false, label: null, approval: { status: "not_started", by: null, at: null, notes: "" } },
    activity: [act(daysAgo(4), "u1", "Opportunity created")],
  },
  {
    id: "OPP-1024",
    customer: "Harborview Cafés",
    contact: { name: "Dana Ricci", email: "dricci@harborview.cafe" },
    product: "Maple-oat breakfast bar, 3-cafe pilot",
    createdBy: "u1",
    createdAt: daysAgo(15),
    stage: "sample_creation",
    stageEnteredAt: daysAgo(9),
    conversations: [
      { by: "u1", at: daysAgo(15), note: "Inbound lead from website. Wants a signature breakfast bar." },
      { by: "u1", at: daysAgo(13), note: "Tasting preferences call: less sweet, visible oats." },
      { by: "u1", at: daysAgo(6), note: "V1 feedback relayed — too dense, wants chewier crumb." },
    ],
    formulations: { requested: true, status: "done", notes: "Reduced binder 8%, swapped to rolled oats. Frozen-stability verified." },
    sampleRequest: {
      qty: "24 bars",
      unitSize: "60 g bar",
      packFormat: "Parchment-wrapped, 12-ct tray",
      allergens: ["Wheat / gluten", "Dairy"],
      certifications: ["Clean label", "RSPO palm oil"],
      shelfLife: "14 days ambient",
      storage: "Ambient",
      notes: "Pilot across 3 cafes — nut-free line required",
      submittedAt: daysAgo(9),
      by: "u2",
    },
    samples: [
      { version: 1, at: daysAgo(8), desc: "Dense crumb, standard maple", feedback: "Customer: too dense, sweetness OK", status: "revised" },
      { version: 2, at: daysAgo(2), desc: "Chewier crumb per formulation change, toasted oat topping", feedback: "", status: "with_customer" },
    ],
    sampleFinalized: false,
    pricing: { status: "requested", base: null, addons: [], invoiceTotal: null, invoiceSentAt: null, poNumber: null, poReceivedAt: null, requestedAt: daysAgo(2) },
    onboarding: { specSource: null, specStatus: "not_started", metadataMapped: false, label: null, approval: { status: "not_started", by: null, at: null, notes: "" } },
    activity: [
      act(daysAgo(15), "u1", "Opportunity created"),
      act(daysAgo(9), "u1", "Sent to Sample Request team + Formulations"),
      act(daysAgo(9), "u2", "Sample request form submitted to Sample Creation"),
      act(daysAgo(8), "u3", "Sample v1 shipped to customer"),
      act(daysAgo(7), "u4", "Formulation revision complete"),
      act(daysAgo(2), "u3", "Sample v2 shipped to customer"),
      act(daysAgo(2), "u1", "Pricing requested — conversation moving forward"),
    ],
    discussion: [
      { by: "u3", at: daysAgo(8), text: "Maya — 'less sweet' from the tasting call: are we talking cutting the maple, or keeping maple but dropping added sugar?" },
      { by: "u1", at: daysAgo(8), text: "Keep the maple flavor, cut added sugar. She specifically wants the maple to read on the label." },
      { by: "u4", at: daysAgo(7), text: "Noted for the reformulation — swapping to rolled oats also reads less sweet. v2 reflects both." },
      { by: "u5", at: daysAgo(2), text: "For pricing: is the 3-cafe pilot volume ~500/wk total or per cafe?" },
    ],
  },
  {
    id: "OPP-1023",
    customer: "Fenway Food Hall",
    contact: { name: "Alicia Grant", email: "agrant@fenwayfoodhall.com" },
    product: "Brown-butter chocolate chunk cookie, food-hall exclusive",
    createdBy: "u1",
    createdAt: daysAgo(22),
    stage: "commercial",
    stageEnteredAt: daysAgo(5),
    conversations: [
      { by: "u1", at: daysAgo(22), note: "Referral from Cape Ann account. High foot-traffic venue." },
      { by: "u1", at: daysAgo(18), note: "They want an exclusive SKU. Sample requested." },
    ],
    formulations: { requested: false, status: "n/a", notes: "" },
    sampleRequest: { qty: "36 cookies", format: "85g cookie", allergens: "Wheat, dairy, soy", notes: "Exclusive SKU", submittedAt: daysAgo(17), by: "u2" },
    samples: [
      { version: 1, at: daysAgo(14), desc: "Standard chunk ratio", feedback: "More browned butter flavor requested", status: "revised" },
      { version: 2, at: daysAgo(9), desc: "Double brown-butter, flaky salt finish", feedback: "Approved by customer tasting panel", status: "finalized" },
    ],
    sampleFinalized: true,
    pricing: {
      status: "invoiced", base: 1.42,
      addons: [{ label: "Refrigerated shipping (weekly)", amount: 180 }, { label: "Exclusive SKU setup fee", amount: 350 }],
      invoiceTotal: 3576, invoiceSentAt: daysAgo(3), poNumber: null, poReceivedAt: null, requestedAt: daysAgo(5), baseSetAt: daysAgo(4),
    },
    onboarding: { specSource: null, specStatus: "not_started", metadataMapped: false, label: null, approval: { status: "not_started", by: null, at: null, notes: "" } },
    activity: [
      act(daysAgo(22), "u1", "Opportunity created"),
      act(daysAgo(17), "u2", "Sample request form submitted"),
      act(daysAgo(9), "u3", "Sample v2 shipped"),
      act(daysAgo(6), "u1", "Sample finalized by customer"),
      act(daysAgo(5), "u1", "Pricing requested"),
      act(daysAgo(4), "u5", "Base price set: $1.42/unit"),
      act(daysAgo(3), "u1", "Invoice sent with shipping + setup add-ons ($3,576)"),
    ],
  },
  {
    id: "OPP-1022",
    customer: "Somerville Winter Market",
    contact: { name: "Nadia Kessler", email: "nadia@somervillewm.org" },
    product: "Spiced pear hand pie, seasonal run",
    createdBy: "u1",
    createdAt: daysAgo(6),
    stage: "discovery",
    stageEnteredAt: daysAgo(1),
    returnInfo: {
      from: "sample_request",
      to: "discovery",
      by: "u2",
      at: daysAgo(1),
      reason: "Allergen requirements and target shelf life are missing from the discovery notes — can't complete the sample request form without them.",
    },
    conversations: [
      { by: "u1", at: daysAgo(6), note: "Seasonal vendor program — wants a hand pie for the winter market run." },
      { by: "u1", at: daysAgo(4), note: "Est. 800 units/week for 10 weeks. Wants a sample before committing." },
    ],
    formulations: { requested: false, status: "n/a", notes: "" },
    sampleRequest: null,
    samples: [],
    sampleFinalized: false,
    pricing: { status: "not_requested", base: null, addons: [], invoiceTotal: null, invoiceSentAt: null, poNumber: null, poReceivedAt: null },
    onboarding: { specSource: null, specStatus: "not_started", metadataMapped: false, label: null, approval: { status: "not_started", by: null, at: null, notes: "" } },
    activity: [
      act(daysAgo(6), "u1", "Opportunity created"),
      act(daysAgo(4), "u1", "Customer wants a sample → pushed to Sample Request team"),
      act(daysAgo(1), "u2", "Sent back to Discovery — allergen requirements and target shelf life missing"),
    ],
  },
  {
    id: "OPP-1021",
    customer: "Nor'easter Provisions",
    contact: { name: "Tom Beaulieu", email: "tom@noreasterprov.com" },
    product: "Cranberry-walnut boule, retail par-baked",
    createdBy: "u1",
    createdAt: daysAgo(39),
    stage: "approval",
    stageEnteredAt: daysAgo(8),
    conversations: [
      { by: "u1", at: daysAgo(39), note: "Regional grocery chain, 11 stores." },
    ],
    formulations: { requested: true, status: "done", notes: "Par-bake profile validated for retail ovens." },
    sampleRequest: { qty: "12 boules", format: "500g par-baked", allergens: "Wheat, walnuts", notes: "Retail bake-off format", submittedAt: daysAgo(35), by: "u2" },
    samples: [
      { version: 1, at: daysAgo(30), desc: "Standard par-bake", feedback: "Approved", status: "finalized" },
    ],
    sampleFinalized: true,
    pricing: {
      status: "po_received", base: 3.1,
      addons: [{ label: "Freight (pallet, weekly)", amount: 260 }],
      invoiceTotal: 8940, invoiceSentAt: daysAgo(20), poNumber: "PO-NE-88412", poReceivedAt: daysAgo(16), requestedAt: daysAgo(24), baseSetAt: daysAgo(22),
    },
    onboarding: {
      specSource: "customer", specStatus: "complete", metadataMapped: true,
      label: { code: "BBC-CWB-500-R2", createdAt: daysAgo(9), by: "u6", status: "created" },
      approval: { status: "pending", by: null, at: null, notes: "" },
      specDoc: "NE-Provisions-spec-v2.pdf (uploaded by customer)",
    },
    activity: [
      act(daysAgo(39), "u1", "Opportunity created"),
      act(daysAgo(16), "u1", "PO received — onboarding started"),
      act(daysAgo(12), "u6", "Customer spec uploaded and mapped to internal metadata"),
      act(daysAgo(9), "u6", "Lot sheet BBC-CWB-500-R2 created"),
      act(daysAgo(8), "u6", "Submitted to Senior Manager for final protocol review"),
    ],
  },
  {
    id: "OPP-1019",
    customer: "Cape Ann Coffee Roasters",
    contact: { name: "Elise Moreau", email: "elise@capeanncoffee.com" },
    product: "Espresso-glazed morning bun, 5 locations",
    createdBy: "u1",
    createdAt: daysAgo(58),
    stage: "manufacturing",
    stageEnteredAt: daysAgo(32),
    conversations: [{ by: "u1", at: daysAgo(58), note: "Long-time prospect, finally ready to outsource pastry." }],
    formulations: { requested: false, status: "n/a", notes: "" },
    sampleRequest: { qty: "20 buns", format: "95g bun", allergens: "Wheat, dairy, egg", notes: "", submittedAt: daysAgo(54), by: "u2" },
    samples: [{ version: 1, at: daysAgo(50), desc: "Espresso glaze, laminated base", feedback: "Approved first pass", status: "finalized" }],
    sampleFinalized: true,
    pricing: {
      status: "po_received", base: 1.85, addons: [{ label: "AM delivery route", amount: 140 }],
      invoiceTotal: 5690, invoiceSentAt: daysAgo(44), poNumber: "PO-CA-2201", poReceivedAt: daysAgo(41), requestedAt: daysAgo(47), baseSetAt: daysAgo(45),
    },
    onboarding: {
      specSource: "internal", specStatus: "complete", metadataMapped: true,
      label: { code: "BBC-EMB-095-C1", createdAt: daysAgo(36), by: "u6", status: "created" },
      approval: { status: "approved", by: "u7", at: daysAgo(32), notes: "All 200-point protocol checks passed offline. Cleared for manufacturing." },
      specDoc: "Internal spec from discovery notes",
    },
    activity: [
      act(daysAgo(58), "u1", "Opportunity created"),
      act(daysAgo(41), "u1", "PO received — onboarding started"),
      act(daysAgo(32), "u7", "Approved → released to manufacturing (26-day cycle)"),
    ],
  },
];
